/********************************************************************
 * Automatically generated by ARUnit
 * Filename: Rte_Main_SWC_Type.h
 * Generated on: Sat Mar 9 1:3:32 GMT+02:00
 ********************************************************************/

#ifndef RTE_MAIN_SWC_TYPE_H
#define RTE_MAIN_SWC_TYPE_H


#include "Rte_Type.h"

#ifdef __cplusplus
	extern "C" {
#endif /* __cplusplus */

/*************************** range types *****************************/


/************************ enumeration types **************************/



#ifdef __cplusplus
} /* extern "C" */
#endif /* __cplusplus */

#endif /* RTE_MAIN_SWC_TYPE_H */
