/********************************************************************
 * Automatically generated by ARUnit
 * Filename: Rte_Empty_For_Test_Type.h
 * Generated on: Wed Feb 7 23:44:23 GMT+02:00
 ********************************************************************/

#ifndef RTE_EMPTY_FOR_TEST_TYPE_H
#define RTE_EMPTY_FOR_TEST_TYPE_H


#include "Rte_Type.h"

#ifdef __cplusplus
	extern "C" {
#endif /* __cplusplus */

/*************************** range types *****************************/


/************************ enumeration types **************************/



#ifdef __cplusplus
} /* extern "C" */
#endif /* __cplusplus */

#endif /* RTE_EMPTY_FOR_TEST_TYPE_H */
