/********************************************************************
 * Automatically generated by ARUnit
 * Filename: Rte_BSW_SWC_Type.h
 * Generated on: Wed Feb 7 23:44:23 GMT+02:00
 ********************************************************************/

#ifndef RTE_BSW_SWC_TYPE_H
#define RTE_BSW_SWC_TYPE_H


#include "Rte_Type.h"

#ifdef __cplusplus
	extern "C" {
#endif /* __cplusplus */

/*************************** range types *****************************/

#define my_uint8_LowerLimit  (0U)
#define my_uint8_UpperLimit (255U)

/************************ enumeration types **************************/



#ifdef __cplusplus
} /* extern "C" */
#endif /* __cplusplus */

#endif /* RTE_BSW_SWC_TYPE_H */
