/********************************************************************
 * Automatically generated by ARUnit
 * Filename: Rte_Type.h
 * Generated on: Wed Feb 7 23:44:23 GMT+02:00
 ********************************************************************/

#ifndef RTE_TYPE_H
#define RTE_TYPE_H


#include "Rte.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */
/**************************** datatypes ******************************/

typedef unsigned char my_uint8;
typedef my_uint8 CAN_FRAME[8];


/********************* mode declaration groups ***********************/


/********************** per instance memories ************************/


/******************* implicit buffer declaration *********************/

typedef struct {
	CAN_FRAME value;
} Rte_DE_CAN_FRAME;

typedef struct {
	my_uint8 value;
} Rte_DE_my_uint8;


/******************** component data structures **********************/

/*********************************************************************
 * component data structure for SWC: Main_SWC
 *********************************************************************/
typedef struct Rte_CDS_Main_SWC
{
	/* Data Handles section*/
	Rte_DE_CAN_FRAME *Main_SWC_Runnable_RP_CAN_Frame_CAN_Frame;
	/* Per-Instance Memory Handles section*/
	/* Inter-runnable Variable Handles section*/
	/* Calibration Parameter Handles section*/
	/* Exclusive-area Handles section*/
	/* Port API Handles section*/
	/* Inter Runnable Variable API Handles section*/
} Rte_CDS_Main_SWC;

/*********************************************************************
 * component data structure for SWC: Empty_For_Test 
 *********************************************************************/
typedef struct Rte_CDS_Empty_For_Test
{
	/* Data Handles section*/
	Rte_DE_CAN_FRAME *Empty_For_Test_Runnable_PP_CAN_Frame_CAN_Frame;
	/* Per-Instance Memory Handles section*/
	/* Inter-runnable Variable Handles section*/
	/* Calibration Parameter Handles section*/
	/* Exclusive-area Handles section*/
	/* Port API Handles section*/
	/* Inter Runnable Variable API Handles section*/
} Rte_CDS_Empty_For_Test;

/*********************************************************************
 * component data structure for SWC: BSW_SWC 
 *********************************************************************/
typedef struct Rte_CDS_BSW_SWC
{
	/* Data Handles section*/
	Rte_DE_my_uint8 *BSW_SWC_Runnable_PP_LED_Warning_LED_Warning;
	Rte_DE_my_uint8 *BSW_SWC_Runnable_PP_Motor_Speed_Motor_Speed;
	/* Per-Instance Memory Handles section*/
	/* Inter-runnable Variable Handles section*/
	/* Calibration Parameter Handles section*/
	/* Exclusive-area Handles section*/
	/* Port API Handles section*/
	/* Inter Runnable Variable API Handles section*/
} Rte_CDS_BSW_SWC;

/*********************************************************************
 * component data structure for SWC: LED_SWC 
 *********************************************************************/
typedef struct Rte_CDS_LED_SWC
{
	/* Data Handles section*/
	Rte_DE_my_uint8 *LED_SWC_Runnable_RP_LED_Warning_LED_Warning;
	/* Per-Instance Memory Handles section*/
	/* Inter-runnable Variable Handles section*/
	/* Calibration Parameter Handles section*/
	/* Exclusive-area Handles section*/
	/* Port API Handles section*/
	/* Inter Runnable Variable API Handles section*/
} Rte_CDS_LED_SWC;

/*********************************************************************
 * component data structure for SWC: Motor_SWC 
 *********************************************************************/
typedef struct Rte_CDS_Motor_SWC
{
	/* Data Handles section*/
	Rte_DE_my_uint8 *Motor_SWC_Runnable_RP_Motor_Speed_Motor_Speed;
	/* Per-Instance Memory Handles section*/
	/* Inter-runnable Variable Handles section*/
	/* Calibration Parameter Handles section*/
	/* Exclusive-area Handles section*/
	/* Port API Handles section*/
	/* Inter Runnable Variable API Handles section*/
} Rte_CDS_Motor_SWC;

/*********************************************************************
 * component data structure for SWC: Composition_SWC 
 *********************************************************************/
typedef struct Rte_CDS_Composition_SWC
{
	/* Data Handles section*/
	/* Per-Instance Memory Handles section*/
	/* Inter-runnable Variable Handles section*/
	/* Calibration Parameter Handles section*/
	/* Exclusive-area Handles section*/
	/* Port API Handles section*/
	/* Inter Runnable Variable API Handles section*/
	uint8 _dummy;
} Rte_CDS_Composition_SWC;


#ifdef __cplusplus
} /* extern "C" */
#endif /* __cplusplus */

#endif /* RTE_TYPE_H */
