/********************************************************************
 * Automatically generated by ARUnit
 * Filename: Rte_Ultrasonic_SWC.h
 * Generated on: Thu Apr 25 15:36:43 EET
 ********************************************************************/

#ifndef RTE_ULTRASONIC_SWC_H
#define RTE_ULTRASONIC_SWC_H

#include "Rte_Ultrasonic_SWC_Type.h"

#ifdef __cplusplus
	extern "C" {
#endif /* __cplusplus */

/**************** component data structure definition ****************/

#ifndef IN_RTE_C
typedef const Rte_CDS_Ultrasonic_SWC * const Rte_Instance;
#endif

/************************* instance handle ***************************/

extern const Rte_CDS_Ultrasonic_SWC * const Rte_Inst_Ultrasonic_SWC;

/************************ application errors *************************/

#define RTE_E_CSI_Get_Distance_E_NOT_OK ((Std_ReturnType)0)
#define RTE_E_CSI_Get_Distance_E_OK ((Std_ReturnType)1)

/*************************** init values *****************************/


/****************** per instance memory definition *******************/


/************************* exclusive areas ***************************/


/************************* RTE API mapping ***************************/

/*****************************************************
 * Port: 		PP_Get_Distance
 * Interface:	CSI_Get_Distance
 * Operation:	Call_Ultrasonic
 *****************************************************/
extern Std_ReturnType Ultrasonic_SWC(my_uint16* Distance) ;


/**************** event triggered runnable entities *******************/


/******** ARUnit-specific function pointers for server call delegates *********/


#ifdef __cplusplus
} /* extern "C" */
#endif /* __cplusplus */

#endif /* RTE_ULTRASONIC_SWC_H */
