/********************************************************************
 * Automatically generated by ARUnit
 * Filename: Rte_Ultrasonic_SWC_Type.h
 * Generated on: Thu Apr 25 15:36:43 EET
 ********************************************************************/

#ifndef RTE_ULTRASONIC_SWC_TYPE_H
#define RTE_ULTRASONIC_SWC_TYPE_H


#include "Rte_Type.h"

#ifdef __cplusplus
	extern "C" {
#endif /* __cplusplus */

/*************************** range types *****************************/

#define my_uint16_LowerLimit  (0U)
#define my_uint16_UpperLimit (65535U)

/************************ enumeration types **************************/



#ifdef __cplusplus
} /* extern "C" */
#endif /* __cplusplus */

#endif /* RTE_ULTRASONIC_SWC_TYPE_H */
