/********************************************************************
 * Automatically generated by ARUnit
 * Filename: Rte_LED_SWC_Type.h
 * Generated on: Sat Mar 9 24:41:11 GMT+02:00
 ********************************************************************/

#ifndef RTE_LED_SWC_TYPE_H
#define RTE_LED_SWC_TYPE_H


#include "Rte_Type.h"

#ifdef __cplusplus
	extern "C" {
#endif /* __cplusplus */

/*************************** range types *****************************/

#define my_uint8_LowerLimit  (0U)
#define my_uint8_UpperLimit (255U)

/************************ enumeration types **************************/



#ifdef __cplusplus
} /* extern "C" */
#endif /* __cplusplus */

#endif /* RTE_LED_SWC_TYPE_H */
