/********************************************************************
 * Automatically generated by ARUnit
 * Filename: Rte_Ultrasonic_SWC_.c
 * Generated on: Thu Apr 25 15:36:43 EET
 ********************************************************************/

#include "string.h"
#include "Rte_Ultrasonic_SWC.h"




const Rte_CDS_Ultrasonic_SWC Rte_Instance_Ultrasonic_SWC = {
0
};

const Rte_CDS_Ultrasonic_SWC * const Rte_Inst_Ultrasonic_SWC = &Rte_Instance_Ultrasonic_SWC;




