/********************************************************************
 * Automatically generated by ARUnit
 * Filename: Rte_EEBL_SWC_Type.h
 * Generated on: Thu Jun 6 18:29:28 EEST
 ********************************************************************/

#ifndef RTE_EEBL_SWC_TYPE_H
#define RTE_EEBL_SWC_TYPE_H


#include "Rte_Type.h"

#ifdef __cplusplus
	extern "C" {
#endif /* __cplusplus */

/*************************** range types *****************************/

#define my_uint8_LowerLimit  (0U)
#define my_uint8_UpperLimit (255U)
#define my_uint16_LowerLimit  (0U)
#define my_uint16_UpperLimit (65535U)

/************************ enumeration types **************************/



#ifdef __cplusplus
} /* extern "C" */
#endif /* __cplusplus */

#endif /* RTE_EEBL_SWC_TYPE_H */
